routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//========== halaman depan atau front end ================
Route::get('/', function () {
    return view('welcome');
});

//========= akses yang berhubungan authentikasi ==========
Auth::routes();

//======= menu user ============
Route::resource("users", "UserController")->middleware('aksesadmin');

//====== menu dashboard ==========
Route::get('/home', 'HomeController@index')->name('home');

//======= menu kuisioner ============
Route::get('/listmaker', 'KuisionerController@listmaker')->middleware('aksesuser');
Route::get('/kuisioner/start/{id}', 'KuisionerController@start')->middleware('aksesuser');
Route::get('/kuisioner/poin/{id}', 'KuisionerController@show_poin')->middleware('aksesuser');
Route::post('/simpan_kuesioner', 'KuisionerController@simpan_kuesioner')->middleware('aksesuser');
Route::resource("kuisioner", "KuisionerController")->middleware('aksesadmin');

app/Kuisioner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kuisioner extends Model
{
    protected $table = 'kuesioner_soal';
}

app/Http/Controllers/KuisionerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;				//untuk percobaan Query Builder

class KuisionerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$data['dtKuisioner'] = \App\Kuisioner::where('pembuat', \Auth::user()->id)->get();
		//$data['dtKuisioner'] = \App\Kuisioner::all();
		$data['aktif_kuisioner'] = 'class=active';
        return view('admin.kuisioner.page_kuisioner', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kuisioner.add_kuisioner', ['aktif_kuisioner' => 'class=active']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		if($request->get('poin_ya') > 100 or $request->get('poin_tidak') > 100){
			$rules['poin_tidak'] = 'required|numeric|min:0|max:100';
			$rules['poin_ya'] = 'required|numeric|min:0|max:100';
		}else{
			if($request->get('poin_ya') > $request->get('poin_tidak')){
				$rules['poin_tidak'] = 'required|numeric|min:0|max:'.(100 - $request->get('poin_ya'));
				$rules['poin_ya'] = 'required|numeric|min:0|max:100';
			}else{
				$rules['poin_tidak'] = 'required|numeric|min:0|max:100';
				$rules['poin_ya'] = 'required|numeric|min:0|max:'.(100 - $request->get('poin_tidak'));
			}
		}
		$rules['soal'] = 'required';
		
        \Validator::make($request->all(), $rules)->validate();
		
		$new_Kuisioner = new \App\Kuisioner;
		$new_Kuisioner->soal = $request->get('soal');
		$new_Kuisioner->poin_ya = $request->get('poin_ya');
		$new_Kuisioner->poin_tidak = $request->get('poin_tidak');
		$new_Kuisioner->pembuat = \Auth::user()->id;
		$new_Kuisioner->save();
		
		return redirect()->route('kuisioner.create')->with('status', 'Kuesioner Berhasil Dibuat..');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kuis'] = \App\Kuisioner::findOrFail($id);
		$data['aktif_kuisioner'] = 'class=active';
        return view('admin.kuisioner.edit_kuisioner', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		
		if($request->get('poin_ya') > 100 or $request->get('poin_tidak') > 100){
			$rules['poin_tidak'] = 'required|numeric|min:0|max:100';
			$rules['poin_ya'] = 'required|numeric|min:0|max:100';
		}else{
			if($request->get('poin_ya') > $request->get('poin_tidak')){
				$rules['poin_tidak'] = 'required|numeric|min:0|max:'.(100 - $request->get('poin_ya'));
				$rules['poin_ya'] = 'required|numeric|min:0|max:100';
			}else{
				$rules['poin_tidak'] = 'required|numeric|min:0|max:100';
				$rules['poin_ya'] = 'required|numeric|min:0|max:'.(100 - $request->get('poin_tidak'));
			}
		}
		$rules['soal'] = 'required';
		
        \Validator::make($request->all(), $rules)->validate();
		
        $kuis = \App\Kuisioner::findOrFail($id);
		$kuis->poin_ya = $request->get('poin_ya');
		$kuis->poin_tidak = $request->get('poin_tidak');
		$kuis->soal = $request->get('soal');
		
		$kuis->save();
		return redirect()->route('kuisioner.edit', [$id])->with('status', 'Soal Kuesioner Berhasil Diubah.. Yeahhh');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
	
	public function listmaker()
    {
		//untuk select data di function ini menggunakan "Query Builder".
		//syarat untuk menggunakan query builder adalah harus mennggil class tertentu, yaitu
		//"use Illuminate\Support\Facades\DB;" , kalau pakek "Eloquent" kita tidak usah menggil class itu, cukup buat model saja..
		
		//query dibawah akan error, tp jika di jalankan lewat mysql phpmyadmin tidak akan error. ndak tau kenapa
		//solusi biar ndak error, mengganti settingan database di "config\database.php"
		//kemudian cari "strict" dan ubah nilainya menjadi false
		$data['dtKuisioner'] = DB::table('users')
			->join('kuesioner_soal', 'kuesioner_soal.pembuat', '=', 'users.id')
			->select('users.*', DB::raw("count(kuesioner_soal.id) as jum_kuis"))
			->groupBy('users.id')
			->orderByRaw('users.id DESC')
			->get();
		$data['dtJawabUser'] = DB::table('kuesioner_soal')
			->join('kuesioner_jawab', 'kuesioner_jawab.soal_id', '=', 'kuesioner_soal.id')
			->select('kuesioner_soal.pembuat', DB::raw("count(kuesioner_jawab.id) as jum_jawab"))
			->where('kuesioner_jawab.penjawab', '=', \Auth::user()->id)
			->groupBy('kuesioner_soal.pembuat')
			->orderByRaw('kuesioner_soal.pembuat DESC')
			->get();
		$data['aktif_kuisuser'] = 'class=active';
        return view('user.kuisioner.page_listmaker', $data);
    }
	
	public function start($id)
    {
		$data['pembuat'] = \App\User::findOrFail($id);
		$data['soal'] = DB::table('kuesioner_soal')
			->select('kuesioner_soal.id', 'kuesioner_soal.soal', 'kuesioner_jawab.jawaban', 'kuesioner_jawab.created_at', 'kuesioner_jawab.updated_at')
            ->leftJoin('kuesioner_jawab', 'kuesioner_soal.id', '=', 'kuesioner_jawab.soal_id')
			->where('kuesioner_soal.pembuat', '=', $id)
			->orderBy('kuesioner_soal.created_at')
            ->paginate(2);
		$data['cek'] = DB::table('kuesioner_soal')
            ->join('kuesioner_jawab', 'kuesioner_jawab.soal_id', '=', 'kuesioner_soal.id')
			->where('kuesioner_soal.pembuat', '=', $id)
            ->select('kuesioner_soal.*')
            ->get();
		$data['aktif_kuisuser'] = 'class=active';
        return view('user.kuisioner.start_kuisioner', $data);
    }
	
	public function simpan_kuesioner(Request $request)
    {
		//$status = array();
		
		for($i=0;$i<$request->get('jumlah');$i++){
			/*
			$dtCek = DB::table('kuesioner_jawab')->where([
				['soal_id', '=', $request->get('identity'.$i)],
				['penjawab', '=', \Auth::user()->id],
			])->get();
			
			if(count($dtCek) > 0){
				$status[$i] = 'update';
			}else{
				$status[$i] = 'create';
			}
			
			$dataInput[$i] = array(
				'created_at' => \Carbon\Carbon::now(),
				'soal_id' => $request->get('identity'.$i),
				'penjawab' => \Auth::user()->id,
				'jawaban' => $request->get('jawab'.$i),
			);
			*/
			
			//jika suah ada datanya, maka update. jika belum maka insert
			//parameter pertama untuk cek kondisi update
			//parameter ke2 untuk yang diupdate atau jika insert, maka parameter 1 dan 2 akan dimerge
			DB::table('kuesioner_jawab')->updateOrInsert(
				['soal_id' => $request->get('identity'.$i), 'penjawab' => \Auth::user()->id],
				['created_at' => \Carbon\Carbon::now(), 'jawaban' => $request->get('jawab'.$i)]
			);
		}
		
		/*
		if(in_array('update', $status)){
			if(in_array('create', $status)){
				//perulangan dtinput
			}else{
				$affected = DB::table('users')
					->where('id', 1)
					->update(['votes' => 1]);
			}
		}else{
			DB::table('kuesioner_jawab')->insert($dataInput);
		}
		*/
		
		return redirect()->back()->with('message','Operation Successful !');
    }
	
	public function show_poin($id)
    {
		$poin = array();
		
		$data['pembuat'] = \App\User::findOrFail($id);
		$dtJawabUser = DB::table('kuesioner_soal')
			->join('kuesioner_jawab', 'kuesioner_jawab.soal_id', '=', 'kuesioner_soal.id')
			->select('kuesioner_soal.*', 'kuesioner_jawab.jawaban as jawaban')
			->where([
				['kuesioner_jawab.penjawab', '=', \Auth::user()->id],
				['kuesioner_soal.pembuat', '=', $id],
			])
			->orderBy('kuesioner_soal.created_at')
			->get();
		
		foreach($dtJawabUser as $dju){
			if($dju->jawaban == 'YA'){
				$poin[] = $dju->poin_ya;
			}else if($dju->jawaban == 'TIDAK'){
				$poin[] = $dju->poin_tidak;
			}else{
				if($dju->poin_tidak > $dju->poin_ya){
					$poin[] = $dju->poin_tidak - $dju->poin_ya;
				}else{
					$poin[] = $dju->poin_ya - $dju->poin_tidak;
				}
			}
		}
		
		$data['poin'] = $poin;
		$data['dtJawabUser'] = $dtJawabUser;
		
		$data['aktif_kuisuser'] = 'class=active';
        return view('user.kuisioner.poin_kuisioner', $data);
    }
}

resources/views/admin/kuisioner/add_kuisioner.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('breadcrumb')
	<h2><b>Add Kuesioner Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{route('kuisioner.index')}}">Kuesioner</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Add</strong>
		</li>
	</ol>
@endsection

@section('content')
	@if(session('status'))
		<div class="alert alert-success">
			{{session('status')}}
		</div>
	@endif
	<div class="row">
        <div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title bg-success">
					<h5>## Add Data Page ##</h5>
				</div>
				<div class="ibox-content">
					<h2> Form Add Data Kuesioner<br></h2>
					<p>
						<strong>Tata Cara Pengisian :</strong>
						Untuk jumlah poin YA dan TIDAK totalnya tidak boleh melebihi 100 poin, kurang boleh. 
						Jadi jika poin YA bernilai 70 poin, maka poin TIDAK harus antara 0 poin dan 30 poin.
						Jika seandainya jumlah kedua poin tidak mencapai seratus, maka sisanya akan digunakan sebagai penilaian kategori poin "KEDUANYA". :)
					</p>
					<form action="{{route('kuisioner.store')}}" method="POST" enctype="multipart/form-data" style="padding-top:20px;">
						@csrf
						<div class="form-group row has-success">
							<label class="col-sm-2 col-form-label text-center"><b>Pembuat Soal</b></label>
							<div class="col-sm-10"><input value="{{Auth::user()->name.' | '.Auth::user()->email}}" type="text" name="nama" class="form-control" readonly></div>
						</div>
						<div class="form-group row has-success">
							<label class="col-sm-2 col-form-label text-center"><b>Poin [Ya]</b></label>
							<div class="col-sm-4">
								<input value="{{old('poin_ya')}}" type="number" name="poin_ya" class="form-control {{$errors->first('poin_ya') ? 'is-invalid' : ''}}" required>
								<div class="invalid-feedback">
									{{$errors->first('poin_ya')}}
								</div>
							</div>
							<label class="col-sm-2 col-form-label text-center"><b>Poin [Tidak]</b></label>
							<div class="col-sm-4">
								<input value="{{old('poin_tidak')}}" type="number" name="poin_tidak" class="form-control {{$errors->first('poin_tidak') ? 'is-invalid' : ''}}" required>
								<div class="invalid-feedback">
									{{$errors->first('poin_tidak')}}
								</div>
							</div>
						</div>
						<div class="form-group row has-success">
							<label class="col-sm-2 col-form-label text-center"><b>Soal</b></label>
							<div class="col-sm-10">
								<textarea name="soal" class="form-control m-b {{$errors->first('soal') ? 'is-invalid' : ''}}" rows="4">{{old('soal')}}</textarea>
								<div class="invalid-feedback">
									{{$errors->first('soal')}}
								</div>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-4 col-sm-offset-2">
								<a href="{{route('kuisioner.index')}}" class="btn btn-warning btn-sm"><< Back</a>
								<button class="btn btn-primary btn-sm" name="btn_submit" type="submit">Save changes</button>
							</div>
						</div>
					</form>
				</div>
				<div class="ibox-footer">
					<span class="float-right"> The righ side of the footer </span>
					This is simple footer example
				</div>
			</div>
        </div>
    </div>
@endsection

resources/views/admin/kuisioner/edit_kuisioner.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('breadcrumb')
	<h2><b>Edit Kuesioner Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{route('kuisioner.index')}}">Kuesioner</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Edit</strong>
		</li>
	</ol>
@endsection

@section('content')
	@if(session('status'))
		<div class="alert alert-success">
			{{session('status')}}
		</div>
	@endif
	<div class="row">
        <div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title bg-success">
					<h5>## Edit Data Page ##</h5>
				</div>
				<div class="ibox-content">
					<h2> Form Edit Data Kuesioner<br></h2>
					<p>
						<strong>Tata Cara Pengisian :</strong>
						Untuk jumlah poin YA dan TIDAK totalnya tidak boleh melebihi 100 poin, kurang boleh. 
						Jadi jika poin YA bernilai 70 poin, maka poin TIDAK harus antara 0 poin dan 30 poin.
						Jika seandainya jumlah kedua poin tidak mencapai seratus, maka sisanya akan digunakan sebagai penilaian kategori poin "KEDUANYA". :)
					</p>
					<form action="{{route('kuisioner.update', [$kuis->id])}}" method="POST" enctype="multipart/form-data" style="padding-top:20px;">
						@csrf
						<input type="hidden" value="PUT" name="_method">
						
						<div class="form-group row">
							<label class="col-sm-2 col-form-label text-center"><b>Pembuat Soal</b></label>
							<div class="col-sm-10"><input value="{{Auth::user()->name.' | '.Auth::user()->email}}" type="text" name="nama" class="form-control" readonly></div>
						</div>
						<div class="form-group row">
							<label class="col-sm-2 col-form-label text-center"><b>Poin [Ya]</b></label>
							<div class="col-sm-4">
								<input value="{{old('poin_ya') ? old('poin_ya') : $kuis->poin_ya}}" type="number" name="poin_ya" 
									class="form-control {{$errors->first('poin_ya') ? 'is-invalid' : ''}}" required>
									<div class="invalid-feedback">
										{{$errors->first('poin_ya')}}
									</div>
							</div>
							<label class="col-sm-2 col-form-label text-center"><b>Poin [Tidak]</b></label>
							<div class="col-sm-4">
								<input value="{{old('poin_tidak') ? old('poin_tidak') : $kuis->poin_tidak}}" type="number" name="poin_tidak" 
									class="form-control {{$errors->first('poin_tidak') ? 'is-invalid' : ''}}" required>
								<div class="invalid-feedback">
									{{$errors->first('poin_tidak')}}
								</div>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-sm-2 col-form-label text-center"><b>Soal</b></label>
							<div class="col-sm-10">
								<textarea name="soal" class="form-control m-b {{$errors->first('soal') ? 'is-invalid' : ''}}" rows="4">{{old('soal') ? old('soal') : $kuis->soal}}</textarea>
								<div class="invalid-feedback">
									{{$errors->first('soal')}}
								</div>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-4 col-sm-offset-2">
								<a href="{{route('kuisioner.index')}}" class="btn btn-warning btn-sm"><< Back</a>
								<button class="btn btn-primary btn-sm" name="btn_submit" type="submit">Save changes</button>
							</div>
						</div>
					</form>
				</div>
				<div class="ibox-footer">
					<span class="float-right"> The righ side of the footer </span>
					This is simple footer example
				</div>
			</div>
        </div>
    </div>
@endsection

resources/views/admin/kuisioner/page_kuisioner.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('css_script')
<link href="{{asset('public/template_inspinia/css/plugins/dataTables/datatables.min.css')}}" rel="stylesheet">
<link href="{{asset('public/template_inspinia/css/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet">
@endsection

@section('breadcrumb')
	<h2><b>Kuesioner Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Kuesioner</strong>
		</li>
	</ol>
@endsection

@section('title_action')
	<p align="right">
		<a href="{{route('kuisioner.create')}}" class="btn btn-success btn-facebook btn-outline" style="margin-top:20px;">
			<i class="fa fa-plus-circle"> </i> Add Kuesioner
		</a>
	</p>
@endsection

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-success">
				<div class="panel-heading">
					<b>Data Kuesioner</b>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover dataTables-example">
							<thead>
								<tr>
									<th>No</th>
									<th>Soal</th>
									<th>Poin YA</th>
									<th>Poin Tidak</th>
									<th>Tanggal</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($dtKuisioner as $index => $dk)
									<tr>
										<td>{{($index + 1)}}</td>
										<td>{{$dk->soal}}</td>
										<td>{{$dk->poin_ya}}</td>
										<td>{{$dk->poin_tidak}}</td>
										<td>{{$dk->created_at}}</td>
										<td>
											<a href="{{route('kuisioner.edit', $dk->id)}}" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</a>
											<button onclick="hapus(1)" type="button" class="btn btn-outline btn-danger"><i class="fa fa-trash"></i> Delete</button>
											<button type="button" class="btn btn-outline btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-search"></i> Preview</button>
										</td>
									</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>No</th>
									<th>Soal</th>
									<th>Poin YA</th>
									<th>Poin Tidak</th>
									<th>Tanggal</th>
									<th>Action</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content animated bounceInRight">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<i class="fa fa-laptop modal-icon"></i>
					<h4 class="modal-title">Modal title</h4>
					<small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
				</div>
				<div class="modal-body">
					<p><strong>Lorem Ipsum is simply dummy</strong> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
						printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
						remaining essentially unchanged.</p>
							<div class="form-group"><label>Sample Input</label> <input type="email" placeholder="Enter your email" class="form-control"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('js_script')
<script src="{{asset('public/template_inspinia/js/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('public/template_inspinia/js/plugins/dataTables/datatables.min.js')}}"></script>
<script src="{{asset('public/template_inspinia/js/plugins/dataTables/dataTables.bootstrap4.min.js')}}"></script>
@endsection

@section('script_tambahan')
<script>
	$(document).ready(function(){
		$('.dataTables-example').DataTable({
			pageLength: 25,
			responsive: true,
			dom: '<"html5buttons"B>lTfgitp',
			buttons: [
				{ extend: 'copy'},
				{extend: 'csv'},
				{extend: 'excel', title: 'ExampleFile'},
				{extend: 'pdf', title: 'ExampleFile'},

				{extend: 'print',
				 customize: function (win){
						$(win.document.body).addClass('white-bg');
						$(win.document.body).css('font-size', '10px');

						$(win.document.body).find('table')
								.addClass('compact')
								.css('font-size', 'inherit');
				}
				}
			]

		});

	});
	
    function hapus(id){
		swal({
			title: "Apakah Anda Yakin..?",
			text: "Data Anda Akan Terhapus Permanen..!",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Ya, Hapus!",
			cancelButtonText: "Tidak, Batalkan!",
			closeOnConfirm: false,
			closeOnCancel: false 
		},
		function (isConfirm) {
			if (isConfirm) {
				$.ajax({
					url: '',
					method: 'post',
					data: {id_karyawan:id},
					dataType: 'json',
					async: false,
					success:function(data){
						if(data.status == true){
							swal({
								title: "Terhapus!", 
								text: "Data Berhasil Dihapus", 
								type: "success"
							}, function(){ 
								location.reload();
							});
						}else{
							swal({
								title: "Gagal Dihapus!", 
								text: "Telah Terjadi Kesalahan..! [001] \n Untuk Info Lebih Lanjut, Harap Hubungi Pihak IT :)", 
								type: "error"
							}, function(){ 
								location.reload();
							});
						}
					},
					error: function(jqXHR, textStatus, errorThrown) {
						swal({
							title: "Gagal Dihapus!", 
							text: "Telah Terjadi Kesalahan..! [002] \n Untuk Info Lebih Lanjut, Harap Hubungi Pihak IT :)", 
							type: "error"
						}, function(){ 
							location.reload();
						});
					}
				});
			} else {
				swal("Dibatalkan", "Data Anda Masih Tersimpan :)", "error");
			}
		});
	}
</script>
@endsection