routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//========== halaman depan atau front end ================
Route::get('/', function () {
    return view('welcome');
});

//========= akses yang berhubungan authentikasi ==========
Auth::routes();

//======= menu user ============
Route::resource("users", "UserController")->middleware('aksesadmin');

//====== menu dashboard ==========
Route::get('/home', 'HomeController@index')->name('home');

//======= menu kuisioner ============
Route::get('/listmaker', 'KuisionerController@listmaker')->middleware('aksesuser');
Route::get('/kuisioner/start/{id}', 'KuisionerController@start')->middleware('aksesuser');
Route::get('/kuisioner/poin/{id}', 'KuisionerController@show_poin')->middleware('aksesuser');
Route::post('/simpan_kuesioner', 'KuisionerController@simpan_kuesioner')->middleware('aksesuser');
Route::resource("kuisioner", "KuisionerController")->middleware('aksesadmin');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$users = \App\User::all();
        return view('admin.user.page_user', ['aktif_user' => 'class=active', 'dtUser' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.add_user', ['aktif_user' => 'class=active']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		\Validator::make($request->all(),[
			"name" => "required|min:5|max:100",
			"username" => "required|min:5|max:20",
			"phone" => "digits_between:10,12",
			"address" => "min:20|max:200",
			"email" => "required|email|unique:App\User,email",
			"password" => "required",
			"password_confirmation" => "required|same:password"
		])->validate();
		
        $new_user = new \App\User;
		
		$new_user->name = $request->get('name');
		$new_user->username = $request->get('username');
		$new_user->roles = json_encode(array('ADMIN'));
		$new_user->name = $request->get('name');
		$new_user->address = $request->get('address');
		$new_user->phone = $request->get('phone');
		$new_user->email = $request->get('email');
		$new_user->password = \Hash::make($request->get('password'));
		
		if($request->file('avatar')){
			$file = $request->file('avatar')->store('avatars', 'public');
			$new_user->avatar = $file;
		}
		
		$new_user->save();
		
		return redirect()->route('users.create')->with('status', 'User successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		$data['user'] = \App\User::findOrFail($id);
		$data['aktif_user'] = 'class=active';
        return view('admin.user.edit_user', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \Validator::make($request->all(), [
			"name" => "required|min:5|max:100",
			"username" => "required|min:5|max:20",
			"phone" => "digits_between:10,12",
			"address" => "min:20|max:200",
		])->validate();
		
        $user = \App\User::findOrFail($id);
		$user->name = $request->get('name');
		$user->address = $request->get('address');
		$user->phone = $request->get('phone');
		$user->username = $request->get('username');
		
		if($request->file('avatar')){
			if($user->avatar && file_exists(storage_path('app/public/' . $user->avatar))){
				\Storage::delete('public/'.$user->avatar);
			}
			$file = $request->file('avatar')->store('avatars', 'public');
			$user->avatar = $file;
		}
		$user->save();
		return redirect()->route('users.edit', [$id])->with('status', 'User succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/add_user.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('breadcrumb')
	<h2><b>Add Users Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{route('users.index')}}">Users</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Add</strong>
		</li>
	</ol>
@endsection

@section('content')
	@if(session('status'))
		<div class="alert alert-success">
			{{session('status')}}
		</div>
	@endif
	<div class="row">
        <div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title bg-primary">
					<h5>## Add Data Page ##</h5>
				</div>
				<div class="ibox-content">
					<h2> Form Add Data User [<b>Only Admin</b>]<br></h2>
					<p>
						<strong>Lorem ipsum dolor</strong>
						Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
					</p>
					<form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data" style="padding-top:20px;">
						@csrf
						<div class="form-group row">
							<label for="name" class="col-sm-2 col-form-label text-center"><b>Name</b></label>
							<div class="col-sm-4">
								<input class="form-control {{$errors->first('name') ? 'is-invalid' : ''}}" placeholder="Full Name" value="{{old('name')}}" type="text" name="name" id="name"/>
								<div class="invalid-feedback">
									{{$errors->first('name')}}
								</div>
							</div>
							<label for="email" class="col-sm-2 col-form-label text-center"><b>Email</b></label>
							<div class="col-sm-4">
								<input value="{{old('email')}}" class="form-control {{$errors->first('email') ? 'is-invalid' : ''}}" placeholder="user@mail.com" type="text" name="email" id="email"/>
								<div class="invalid-feedback">
									{{$errors->first('email')}}
								</div>
							</div>
						</div>
						<div class="form-group row">
							<label for="username" class="col-sm-2 col-form-label text-center"><b>Username</b></label>
							<div class="col-sm-4">
								<input value="{{old('username')}}"  class="form-control {{$errors->first('username') ? 'is-invalid' : ''}}" placeholder="username" type="text" name="username" id="username"/>
								<div class="invalid-feedback">
									{{$errors->first('username')}}
								</div>
							</div>
							<label for="access" class="col-sm-2 col-form-label text-center"><b>Access</b></label>
							<div class="col-sm-4">
								<input value="ADMIN" type="text" name="access" class="form-control" readonly>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-6">
								<div class="row">
									<label for="phone" class="col-sm-4 col-form-label text-center"><b>Phone Number</b></label>
									<div class="col-sm-8">
										<input value="{{old('phone')}}" type="text" name="phone" class="form-control {{$errors->first('phone') ? 'is-invalid' : ''}}">
										<div class="invalid-feedback">
											{{$errors->first('phone')}}
										</div>
									</div>
								</div>
								<br>
								<div class="row">
									<label for="avatar" class="col-sm-4 col-form-label text-center"><b>Avatar Image</b></label>
									<div class="col-sm-8">
										<div class="custom-file">
											<input id="avatar" name="avatar" type="file" class="form-control custom-file-input {{$errors->first('avatar') ? 'is-invalid' : ''}}">
											<label for="avatar" class="custom-file-label">Choose file...</label>
											<div class="invalid-feedback">
												{{$errors->first('avatar')}}
											</div>
										</div>
									</div>
								</div>
							</div>
							<label for="address" class="col-sm-2 col-form-label text-center"><b>Address</b></label>
							<div class="col-sm-4">
								<textarea name="address" id="address" rows="4" class="form-control {{$errors->first('address') ? 'is-invalid' : ''}}">{{old('address')}}</textarea>
								<div class="invalid-feedback">
									{{$errors->first('address')}}
								</div>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<label class="col-sm-2 col-form-label text-center"><b>Password</b></label>
							<div class="col-sm-4">
								<input class="form-control {{$errors->first('password') ? 'is-invalid' : ''}}" placeholder="password" type="password" name="password" id="password"/>
								<div class="invalid-feedback">
									{{$errors->first('password')}}
								</div>
							</div>
							<label class="col-sm-2 col-form-label text-center"><b>Password Confirmation</b></label>
							<div class="col-sm-4">
								<input class="form-control {{$errors->first('password_confirmation') ? 'is-invalid' : ''}}" placeholder="password confirmation" type="password" name="password_confirmation" id="password_confirmation"/>
								<div class="invalid-feedback">
									{{$errors->first('password_confirmation')}}
								</div>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-4 col-sm-offset-2">
								<a href="{{route('users.index')}}" class="btn btn-warning btn-sm"><< Back</a>
								<button class="btn btn-primary btn-sm" name="btn_submit" type="submit">Save changes</button>
							</div>
						</div>
					</form>
				</div>
				<div class="ibox-footer">
					<span class="float-right"> The righ side of the footer </span>
					This is simple footer example
				</div>
			</div>
        </div>
    </div>
@endsection

@section('script_tambahan')
<script>
	$(document).ready(function () {
		$('.custom-file-input').on('change', function() {
			let fileName = $(this).val().split('\\').pop();
			$(this).next('.custom-file-label').addClass("selected").html(fileName);
		});
	});
</script>
@endsection

resources/views/admin/user/edit_user.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('breadcrumb')
	<h2><b>Edit Users Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{route('users.index')}}">Users</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Edit</strong>
		</li>
	</ol>
@endsection

@section('content')
	@if(session('status'))
		<div class="alert alert-success">
			{{session('status')}}
		</div>
	@endif
	<div class="row">
        <div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title bg-primary">
					<h5>## Edit Data Page ##</h5>
				</div>
				<div class="ibox-content">
					<h2> Form Edit Data User <br></h2>
					<p>
						<strong>Lorem ipsum dolor</strong>
						Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
					</p>
					<form action="{{route('users.update', [$user->id])}}" method="POST" enctype="multipart/form-data" style="padding-top:20px;">
						@csrf
						<input type="hidden" value="PUT" name="_method">
						
						<div class="form-group row">
							<label for="name" class="col-sm-2 col-form-label text-center"><b>Name</b></label>
							<div class="col-sm-4">
								<input class="form-control {{$errors->first('name') ? 'is-invalid' : ''}}" placeholder="Full Name" 
									value="{{old('name') ? old('name') : $user->name}}" type="text" name="name" id="name"/>
								<div class="invalid-feedback">
									{{$errors->first('name')}}
								</div>
							</div>
							<label for="email" class="col-sm-2 col-form-label text-center"><b>Email</b></label>
							<div class="col-sm-4">
								<input value="{{$user->email}}" class="form-control" type="text" name="email" id="email" disabled />
							</div>
						</div>
						<div class="form-group row">
							<label for="username" class="col-sm-2 col-form-label text-center"><b>Username</b></label>
							<div class="col-sm-4">
								<input value="{{old('username') ? old('username') : $user->username}}" class="form-control {{$errors->first('username') ? 'is-invalid' : ''}}" 
									placeholder="username" type="text" name="username" id="username"/>
								<div class="invalid-feedback">
									{{$errors->first('username')}}
								</div>
							</div>
							<label for="access" class="col-sm-2 col-form-label text-center"><b>Access</b></label>
							<div class="col-sm-4">
								<input value="<?php foreach(json_decode($user->roles) as $akses){ echo '| '.$akses.' | '; } ?>" 
									type="text" name="access" class="form-control" readonly>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-6">
								<div class="row">
									<label for="phone" class="col-sm-4 col-form-label text-center"><b>Phone Number</b></label>
									<div class="col-sm-8">
										<input value="{{old('phone') ? old('phone') : $user->phone}}" type="number" name="phone" class="form-control {{$errors->first('phone') ? 'is-invalid' : ''}}">
										<div class="invalid-feedback">
											{{$errors->first('phone')}}
										</div>
									</div>
								</div>
								<br>
								<div class="row">
									<label for="address" class="col-sm-4 col-form-label text-center"><b>Address</b></label>
									<div class="col-sm-8">
										<textarea name="address" id="address" rows="4" class="form-control {{$errors->first('address') ? 'is-invalid' : ''}}">{{old('address') ? old('address') : $user->address}}</textarea>
										<div class="invalid-feedback">
											{{$errors->first('address')}}
										</div>
									</div>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="row">
									<label for="avatar" class="col-sm-4 col-form-label text-center"><b>Current Avatar </b></label>
									<div class="col-sm-8 text-center">
										@if($user->avatar)
											<img src="{{asset('public/storage/'.$user->avatar)}}" height="100px" />
										@else
											<h3> No avatar </h3>
										@endif
									</div>
								</div>
								<br>
								<div class="row">
									<label for="avatar" class="col-sm-4 col-form-label text-center"><b>Avatar Image</b></label>
									<div class="col-sm-8">
										<div class="custom-file">
											<input id="avatar" name="avatar" type="file" class="form-control custom-file-input {{$errors->first('avatar') ? 'is-invalid' : ''}}">
											<label for="avatar" class="custom-file-label">Choose file...</label>
											<div class="invalid-feedback">
												{{$errors->first('avatar')}}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="hr-line-dashed"></div>
						<div class="form-group row">
							<div class="col-sm-4 col-sm-offset-2">
								<a href="{{route('users.index')}}" class="btn btn-warning btn-sm"><< Back</a>
								<button class="btn btn-primary btn-sm" name="btn_submit" type="submit">Save changes</button>
							</div>
						</div>
					</form>
				</div>
				<div class="ibox-footer">
					<span class="float-right"> The righ side of the footer </span>
					This is simple footer example
				</div>
			</div>
        </div>
    </div>
@endsection

@section('script_tambahan')
<script>
	$(document).ready(function () {
		$('.custom-file-input').on('change', function() {
			let fileName = $(this).val().split('\\').pop();
			$(this).next('.custom-file-label').addClass("selected").html(fileName);
		});
	});
</script>
@endsection

resources/views/admin/user/page_user.blade.php
@extends('layouts.template_inspinia')

@section('title') Dashboard @endsection

@section('css_script')
<link href="{{asset('public/template_inspinia/css/plugins/dataTables/datatables.min.css')}}" rel="stylesheet">
<link href="{{asset('public/template_inspinia/css/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet">
@endsection

@section('breadcrumb')
	<h2><b>Users Page</b></h2>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Laravel Pro</a>
		</li>
		<li class="breadcrumb-item active">
			<strong>Users</strong>
		</li>
	</ol>
@endsection

@section('title_action')
	<p align="right">
		<a href="{{route('users.create')}}" class="btn btn-success btn-facebook btn-outline" style="margin-top:20px;">
			<i class="fa fa-plus-circle"> </i> Add User
		</a>
	</p>
@endsection

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<b>Data User</b>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover dataTables-example">
							<thead>
								<tr>
									<th>No</th>
									<th>Name</th>
									<th>Email</th>
									<th>Access</th>
									<th>Avatar</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($dtUser as $index => $du)
									<tr>
										<td>{{($index + 1)}}</td>
										<td>{{$du->name}}</td>
										<td>{{$du->email}}</td>
										<td>
											@foreach(json_decode($du->roles) as $akses)
												{{ '| '.$akses.' | ' }}
											@endforeach
										</td>
										<td>
										@if($du->avatar)
											<img src="{{asset('public/storage/'.$du->avatar)}}" width="70px"/>
										@else
											N/A
										@endif
										</td>
										<td>
											<a href="{{route('users.edit',[$du->id])}}" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</a>
											<button onclick="hapus(1)" type="button" class="btn btn-outline btn-danger"><i class="fa fa-trash"></i> Delete</button>
											<button type="button" class="btn btn-outline btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-search"></i> Preview</button>
										</td>
									</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>No</th>
									<th>Name</th>
									<th>Email</th>
									<th>Access</th>
									<th>Avatar</th>
									<th>Action</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content animated bounceInRight">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<i class="fa fa-laptop modal-icon"></i>
					<h4 class="modal-title">Modal title</h4>
					<small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
				</div>
				<div class="modal-body">
					<p><strong>Lorem Ipsum is simply dummy</strong> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
						printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
						remaining essentially unchanged.</p>
							<div class="form-group"><label>Sample Input</label> <input type="email" placeholder="Enter your email" class="form-control"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('js_script')
<script src="{{asset('public/template_inspinia/js/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('public/template_inspinia/js/plugins/dataTables/datatables.min.js')}}"></script>
<script src="{{asset('public/template_inspinia/js/plugins/dataTables/dataTables.bootstrap4.min.js')}}"></script>
@endsection

@section('script_tambahan')
<script>
	$(document).ready(function(){
		$('.dataTables-example').DataTable({
			pageLength: 25,
			responsive: true,
			dom: '<"html5buttons"B>lTfgitp',
			buttons: [
				{ extend: 'copy'},
				{extend: 'csv'},
				{extend: 'excel', title: 'ExampleFile'},
				{extend: 'pdf', title: 'ExampleFile'},

				{extend: 'print',
				 customize: function (win){
						$(win.document.body).addClass('white-bg');
						$(win.document.body).css('font-size', '10px');

						$(win.document.body).find('table')
								.addClass('compact')
								.css('font-size', 'inherit');
				}
				}
			]

		});

	});
	
    function hapus(id){
		swal({
			title: "Apakah Anda Yakin..?",
			text: "Data Anda Akan Terhapus Permanen..!",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Ya, Hapus!",
			cancelButtonText: "Tidak, Batalkan!",
			closeOnConfirm: false,
			closeOnCancel: false 
		},
		function (isConfirm) {
			if (isConfirm) {
				$.ajax({
					url: '',
					method: 'post',
					data: {id_karyawan:id},
					dataType: 'json',
					async: false,
					success:function(data){
						if(data.status == true){
							swal({
								title: "Terhapus!", 
								text: "Data Berhasil Dihapus", 
								type: "success"
							}, function(){ 
								location.reload();
							});
						}else{
							swal({
								title: "Gagal Dihapus!", 
								text: "Telah Terjadi Kesalahan..! [001] \n Untuk Info Lebih Lanjut, Harap Hubungi Pihak IT :)", 
								type: "error"
							}, function(){ 
								location.reload();
							});
						}
					},
					error: function(jqXHR, textStatus, errorThrown) {
						swal({
							title: "Gagal Dihapus!", 
							text: "Telah Terjadi Kesalahan..! [002] \n Untuk Info Lebih Lanjut, Harap Hubungi Pihak IT :)", 
							type: "error"
						}, function(){ 
							location.reload();
						});
					}
				});
			} else {
				swal("Dibatalkan", "Data Anda Masih Tersimpan :)", "error");
			}
		});
	}
</script>
@endsection